name: Test building the project in different environments

on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        os:
          - { image: "ubuntu:24.04", dockerfile: "Dockerfile_DEBIAN" }
        config:
          - drm-egl-2d
          - drm-egl-3d
          - fbdev
          - glfw
          - glfw-3d
          - sdl
          - wayland
          - wayland-egl
      fail-fast: false

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the Docker image
        run: |
          docker build \
            --build-arg BASE_OS=${{ matrix.os.image }} \
            -f docker/${{ matrix.os.dockerfile }} \
            -t test_${{ matrix.os.image }} .

      - name: Build project with ${{ matrix.config }}
        run: |
          sudo rm -rf build/ bin/
          docker run --rm -v "$(pwd)":/workdir -t test_${{ matrix.os.image }} \
          /bin/bash -ec "
            cmake -DWERROR=ON -DCONFIG=${{ matrix.config }} -B build && \
            cmake --build build -j\$(nproc) && \
            ldd build/bin/lvglsim
          "

